Update build-padavan.yml

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -1,67 +1,142 @@
-name: Build Padavan With VNT
+#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
+name: Build Padavan
 
 on: 
-  workflow_dispatch:
+  release:
+    types: [published]
   push:
     tags:
-      - 'v*'
+    - 'v*'
+  #  branches: 
+  #    - master
+#  schedule:
+#    - cron: 0 8 * * 5
+  watch:
+    types: [started]
 
 jobs:
   build:
     runs-on: ubuntu-20.04
-    env:
-      TNAME: WR1200JS  # 修改为你的设备型号（需匹配configs/templates下的文件名）
-      VNT_VERSION: v1.2.16  # VNT版本号<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">3</a>
+    if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-    - name: Checkout source
-      uses: actions/checkout@v4
-
-    - name: Install dependencies
+    - name: Checkout
+      uses: actions/checkout@master
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
       run: |
         sudo apt-get update
-        sudo apt-get install -y unzip libtool-bin cmake gperf bison flex \
-        gettext automake autopoint texinfo build-essential pkg-config zlib1g-dev
-
-    - name: Setup toolchain
+        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
+        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
+    - name: Clone source code
+      env:
+        KERNEL: 3.4
       run: |
-        git clone --depth=1 https://github.com/chongshengB/rt-n56u /opt/rt-n56u
+        sudo chmod -R 777 /opt
+        if [ $KERNEL = "4.4" ] ; then
+        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
+        else
+        #git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
+        git clone --depth=1 https://e.coding.net/hanwckf/rt-n56u/padavan.git /opt/rt-n56u
+        fi
         cd /opt/rt-n56u/toolchain-mipsel
-        sudo bash dl_toolchain.sh
-
-    - name: Integrate VNT
+        sudo sh dl_toolchain.sh
+        #sudo ./clean_toolchain
+        #sudo ./build_toolchain
+        sudo mkdir -p /opt/images/
+    - name: Build Firmware
+      env:
+        TNAME: WR1200JS
+        KERNEL: 3.4
       run: |
-        # 下载VNT二进制（含重试机制）<a target="_blank" href="https://github.com/huazhuangnan/actions-build-padavan-openwrt" class="hitref" data-title="GitHub Action 学习实例- 自动编译padavan 和openWrt" data-snippet='前言 · openwrt 单独参数及功能说明 · padavan 单独参数及功能说明 · 下载编译完成固件 · 更新日志 · 本地编译 · github 编译方法 · 目录说明.' data-url="https://github.com/huazhuangnan/actions-build-padavan-openwrt">8</a>
-        sudo mkdir -p /opt/rt-n56u/trunk/user/scripts
-        for i in {1..3}; do
-          wget https://github.com/vnt-dev/vnt/releases/download/${{ env.VNT_VERSION }}/vnt-mipsel \
-            -O /opt/rt-n56u/trunk/user/scripts/vnt && break || sleep 15
-        done
-        
-        # 备用下载源<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">3</a>
-        [ ! -f /opt/rt-n56u/trunk/user/scripts/vnt ] && \
-          wget https://cdn.jsdelivr.net/gh/vnt-dev/vnt@${{ env.VNT_VERSION }}/bin/mipsel/vnt \
-          -O /opt/rt-n56u/trunk/user/scripts/vnt
-        
-        sudo chmod +x /opt/rt-n56u/trunk/user/scripts/vnt
-        echo -e '#!/bin/sh\n/opt/etc/storage/vnt &' | sudo tee /opt/rt-n56u/trunk/user/scripts/post_wan_script.sh
-        sudo chmod +x /opt/rt-n56u/trunk/user/scripts/post_wan_script.sh
-
-    - name: Build firmware
-      run: |
+        # 创建目录并设置安全权限
+        sudo mkdir -p /opt/rt-n56u /opt/images
+        sudo chmod 755 /opt/rt-n56u /opt/images
         cd /opt/rt-n56u/trunk
-        sudo cp configs/templates/${{ env.TNAME }}.config .config
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        sudo echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        sudo cp -f configs/templates/$TNAME.config .config
         
-        # 配置VNT集成<a target="_blank" href="https://github.com/lmq8267/padavan-KVR" class="hitref" data-title="修改自用的Padavan-KVR 3.4 透明主题 - GitHub" data-snippet='修改自用的Padavan-KVR 3.4 透明主题，添加了一些插件（VNT 皎月连CloudFlared Lucky Alist Tailscale等） - lmq8267/padavan-KVR.' data-url="https://github.com/lmq8267/padavan-KVR">3</a><a target="_blank" href="https://github.com/huazhuangnan/actions-build-padavan-openwrt" class="hitref" data-title="GitHub Action 学习实例- 自动编译padavan 和openWrt" data-snippet='前言 · openwrt 单独参数及功能说明 · padavan 单独参数及功能说明 · 下载编译完成固件 · 更新日志 · 本地编译 · github 编译方法 · 目录说明.' data-url="https://github.com/huazhuangnan/actions-build-padavan-openwrt">8</a>
-        echo "CONFIG_FIRMWARE_INCLUDE_VNT=y" | sudo tee -a .config
-        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config
-        
-        sudo ./clear_tree
-        sudo ./build_firmware_modify ${{ env.TNAME }} 0
-        sudo mv images/*.trx $GITHUB_WORKSPACE/
+        # 添加vnt-cli二进制文件到固件
+        sudo mkdir -p user/usr/bin
+        sudo wget https://github.com/lmq8267/vnt-cli/releases/download/1.2.16/vnt-cli_mipsel-unknown-linux-musl -O user/usr/bin/vnt-cli
+        sudo chmod +x user/usr/bin/vnt-cli
 
-    - name: Upload artifact
-      uses: actions/upload-artifact@v4
+        sudo sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
+        ################################################################################################
+        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
+        ################################################################################################
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
+        sudo sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
+        sudo sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
+        ######################################################################
+        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
+        ######################################################################
+        if [ $KERNEL = "4.4" ] ; then
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_XRAY=n" >> .config #集成xray执行文件  ~4.5M
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config #ddnsto  ~0.5M
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config  #阿里云盘  ~3m
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
+        else
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config #内网穿透FRPC
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
+        sudo echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
+        fi
+        #########################################################################################
+        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
+        #格式如下：
+        #sed -i '/自定义项/d' .config
+        #echo "自定义项=y" >> .config
+        #########################################################################################
+        sudo ./clear_tree
+        sudo ./build_firmware_modify $TNAME 0
+        sudo mv -f images/*.trx /opt/images/
+    - name : Upload packages
+      uses: actions/upload-artifact@master
+      if: always()
       with:
         name: Padavan-WR1200JS
-        path: $GITHUB_WORKSPACE/*.trx
+        path: /opt/images
